# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'UI.ui'
##
## Created by: Qt User Interface Compiler version 6.5.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QLabel,
    QMainWindow, QPushButton, QSizePolicy, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(371, 243)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.get_btn = QPushButton(self.centralwidget)
        self.get_btn.setObjectName(u"get_btn")
        self.get_btn.setGeometry(QRect(70, 51, 101, 21))
        self.statusbar = QFrame(self.centralwidget)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setGeometry(QRect(0, 220, 371, 21))
        self.statusbar.setFrameShape(QFrame.StyledPanel)
        self.statusbar.setFrameShadow(QFrame.Raised)
        self.label = QLabel(self.statusbar)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(5, 2, 54, 17))
        self.statusbar_txt = QLabel(self.statusbar)
        self.statusbar_txt.setObjectName(u"statusbar_txt")
        self.statusbar_txt.setGeometry(QRect(60, 2, 301, 17))
        self.type_box = QComboBox(self.centralwidget)
        self.type_box.setObjectName(u"type_box")
        self.type_box.setGeometry(QRect(70, 30, 101, 16))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 30, 31, 17))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 10, 41, 17))
        self.room_box = QComboBox(self.centralwidget)
        self.room_box.setObjectName(u"room_box")
        self.room_box.setGeometry(QRect(70, 10, 101, 16))
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(220, 80, 151, 141))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.win_txt = QLabel(self.frame)
        self.win_txt.setObjectName(u"win_txt")
        self.win_txt.setGeometry(QRect(90, 100, 54, 17))
        self.label_5 = QLabel(self.frame)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 40, 54, 17))
        self.fon_txt = QLabel(self.frame)
        self.fon_txt.setObjectName(u"fon_txt")
        self.fon_txt.setGeometry(QRect(90, 40, 54, 17))
        self.label_6 = QLabel(self.frame)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 70, 61, 17))
        self.boom_txt = QLabel(self.frame)
        self.boom_txt.setObjectName(u"boom_txt")
        self.boom_txt.setGeometry(QRect(90, 70, 54, 17))
        self.label_4 = QLabel(self.frame)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(40, 10, 71, 17))
        self.label_7 = QLabel(self.frame)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 100, 54, 17))
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(210, 10, 91, 17))
        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(190, 0, 181, 81))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.get_arch_btn = QPushButton(self.frame_2)
        self.get_arch_btn.setObjectName(u"get_arch_btn")
        self.get_arch_btn.setGeometry(QRect(20, 51, 84, 21))
        self.arch_sport_box = QComboBox(self.frame_2)
        self.arch_sport_box.setObjectName(u"arch_sport_box")
        self.arch_sport_box.setGeometry(QRect(20, 30, 84, 16))
        self.arch_date_txt = QLabel(self.frame_2)
        self.arch_date_txt.setObjectName(u"arch_date_txt")
        self.arch_date_txt.setGeometry(QRect(110, 10, 71, 17))
        self.label_9 = QLabel(self.frame_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(114, 28, 41, 17))
        self.days_txt = QLabel(self.frame_2)
        self.days_txt.setObjectName(u"days_txt")
        self.days_txt.setGeometry(QRect(155, 28, 16, 17))
        self.minus_btn = QPushButton(self.frame_2)
        self.minus_btn.setObjectName(u"minus_btn")
        self.minus_btn.setGeometry(QRect(114, 51, 21, 20))
        self.plus_btn = QPushButton(self.frame_2)
        self.plus_btn.setObjectName(u"plus_btn")
        self.plus_btn.setGeometry(QRect(144, 51, 21, 20))
        self.frame_3 = QFrame(self.centralwidget)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(0, 0, 191, 81))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(50, 90, 131, 20))
        self.analysis_box = QComboBox(self.centralwidget)
        self.analysis_box.setObjectName(u"analysis_box")
        self.analysis_box.setGeometry(QRect(52, 119, 91, 16))
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 118, 41, 17))
        self.calc_btn = QPushButton(self.centralwidget)
        self.calc_btn.setObjectName(u"calc_btn")
        self.calc_btn.setGeometry(QRect(150, 119, 61, 16))
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 145, 61, 17))
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 170, 54, 17))
        self.total_txt = QLabel(self.centralwidget)
        self.total_txt.setObjectName(u"total_txt")
        self.total_txt.setGeometry(QRect(60, 145, 54, 17))
        self.found_txt = QLabel(self.centralwidget)
        self.found_txt.setObjectName(u"found_txt")
        self.found_txt.setGeometry(QRect(60, 170, 54, 17))
        self.show_btn = QPushButton(self.centralwidget)
        self.show_btn.setObjectName(u"show_btn")
        self.show_btn.setGeometry(QRect(150, 145, 61, 70))
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 195, 54, 17))
        self.tuning_txt = QLabel(self.centralwidget)
        self.tuning_txt.setObjectName(u"tuning_txt")
        self.tuning_txt.setGeometry(QRect(60, 195, 31, 17))
        self.minus_btn_2 = QPushButton(self.centralwidget)
        self.minus_btn_2.setObjectName(u"minus_btn_2")
        self.minus_btn_2.setGeometry(QRect(90, 195, 21, 20))
        self.plus_btn_2 = QPushButton(self.centralwidget)
        self.plus_btn_2.setObjectName(u"plus_btn_2")
        self.plus_btn_2.setGeometry(QRect(120, 195, 21, 20))
        MainWindow.setCentralWidget(self.centralwidget)
        self.frame_3.raise_()
        self.frame_2.raise_()
        self.get_btn.raise_()
        self.statusbar.raise_()
        self.type_box.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.room_box.raise_()
        self.frame.raise_()
        self.label_8.raise_()
        self.label_10.raise_()
        self.analysis_box.raise_()
        self.label_11.raise_()
        self.calc_btn.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.total_txt.raise_()
        self.found_txt.raise_()
        self.show_btn.raise_()
        self.label_14.raise_()
        self.tuning_txt.raise_()
        self.minus_btn_2.raise_()
        self.plus_btn_2.raise_()

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"HandyCapper", None))
        self.get_btn.setText(QCoreApplication.translate("MainWindow", u"GET LINE", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Status:", None))
        self.statusbar_txt.setText("")
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Type", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Room", None))
        self.win_txt.setText(QCoreApplication.translate("MainWindow", u"Unstable", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Fonbet", None))
        self.fon_txt.setText(QCoreApplication.translate("MainWindow", u"Unstable", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Betboom", None))
        self.boom_txt.setText(QCoreApplication.translate("MainWindow", u"Unstable", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Connection", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Winline", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Rescent date:", None))
        self.get_arch_btn.setText(QCoreApplication.translate("MainWindow", u"GET ARCHIVE", None))
        self.arch_date_txt.setText("")
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Days:", None))
        self.days_txt.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.minus_btn.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.plus_btn.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Inefficiency Analysis", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Sport:", None))
        self.calc_btn.setText(QCoreApplication.translate("MainWindow", u"SEARCH", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Total:", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Found:", None))
        self.total_txt.setText("")
        self.found_txt.setText("")
        self.show_btn.setText(QCoreApplication.translate("MainWindow", u"SHOW\n"
"RESULTS", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Tuning:", None))
        self.tuning_txt.setText("")
        self.minus_btn_2.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.plus_btn_2.setText(QCoreApplication.translate("MainWindow", u"+", None))
    # retranslateUi

